allowBuilds:
  esbuild: true
  msw: true
  sharp: true
autoInstallPeers: true
engineStrict: true
managePackageManagerVersions: true
minimumReleaseAge: 0
packageManagerStrict: true
packageManagerStrictVersion: true
resolutionMode: highest
strictPeerDependencies: false
